[package]
name = "qaptivator/roblox-matrix-library"
description = "Roblox Library to perform basic matrix operations"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
